### ISSUE TITLE
OneLine initializer cant find CurrentInspector in 2019.2a

### ISSUE THREAD

**Issue by kewur** [slavniyteo/one-line#34]
After upgrading to 2019.2a OneLine initializer fails with "OneLine can not initialize Inspector Window Utility. 
You may experience some performance issues. 
Please create an issue on https://github.com/slavniyteo/one-line/ and we will repair it."

The problem is that on the Initialize() call the currentInspector window is trying to be reflected and stored in the "window" variable. Unity seems to have removed the "s_CurrentInspectorWindow" field from InspectorWindow. 

OneLine still manages to work though so the only problem is performance wise probably.

**Comment by slavniyteo** [comment]
Thank you for reporting, I'll look at it tomorrow

сб, 30 марта 2019, 19:06 Efe Burak <notifications@github.com>:

**Comment by slavniyteo** [comment]
As you said, the problem is that they\`ve removed internal property `InspectorWindow.s_CurrentInspectorWindow`. 

Anyway, it doesn't affect OneLine functionality except it brokes culling optimization (do not draw properties which aren't visible on the window). And you'll leak it only if you manage really big scriptable objects  with thousands lines.

Unfortunately I don't work with Unity right now. But whey they release 2019.2 and publish Unity's source  code, I'll try to repair this optimization.

I keep this issue open in order to repair this functionality in the future.

---

**To disable the error message**, go to `Window/OneLineSettings` and switch off the Culling column (the second from the right).

**Comment by slavniyteo** [comment]
Closed with [#v0.5.2](https://github.com/slavniyteo/one-line/releases/tag/v0.5.2)
