### ISSUE TITLE
UPM Support

### ISSUE THREAD

**Issue by phobos2077** [slavniyteo/one-line#36]
Please change repository structure so this can be used as an actual UPM package from github URL. See this repo for an example:
https://github.com/xsduan/unity-hierarchy-folders

**Comment by slavniyteo** [comment]
I'll do it in a few days, thank you for the link.

**Comment by slavniyteo** [comment]
Ok, when I was saying **a few** I didn't mean something like *"I'll do it on 20th of July"* but today I've added UPM support to [RectEx](https://github.com/slavniyteo/rect-ex), which is a dependency of OneLine. Next time I'll have time to spare, I'll refactor OneLine as well.

Could you check if I did it right, please? It works for me but who knows? I've never used UPM before so there are might be gotchas I don't know about.

---

Actually, I'm not a Unity developer for last two years and my last production experience with Unity is based on Unity v5. That's why I know nothing about UPM and it took me months to overcome procrastination and find out what it is.

**Comment by slavniyteo** [comment]
Done. 

I added an **Installation** section to [Readme](https://github.com/slavniyteo/one-line#installation). 

I close it. Please, reopen if necessary.
